name: glance_widget
description: Create instant-updating home screen widgets for Android (Jetpack Glance) and iOS (WidgetKit). Supports Simple, Progress, and List widget templates.
version: 0.3.0
homepage: https://github.com/abdullah017/glance_widget
repository: https://github.com/abdullah017/glance_widget
issue_tracker: https://github.com/abdullah017/glance_widget/issues
documentation: https://github.com/abdullah017/glance_widget#readme

topics:
  - widget
  - android
  - ios
  - glance
  - widgetkit

environment:
  sdk: ^3.10.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  glance_widget_platform_interface: ^0.3.0
  glance_widget_android: ^0.2.0
  glance_widget_ios: ^0.2.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: glance_widget_android
      ios:
        default_package: glance_widget_ios
