name: glance_widget_ios
description: iOS implementation of the glance_widget plugin using WidgetKit.
version: 0.2.1
homepage: https://github.com/abdullah017/glance_widget
repository: https://github.com/abdullah017/glance_widget/tree/master/glance_widget_ios
issue_tracker: https://github.com/abdullah017/glance_widget/issues

environment:
  sdk: ^3.10.0
  flutter: ">=3.10.0"

flutter:
  plugin:
    implements: glance_widget
    platforms:
      ios:
        pluginClass: GlanceWidgetIosPlugin

dependencies:
  flutter:
    sdk: flutter
  glance_widget_platform_interface: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
