name: glance_widget_platform_interface
description: A common platform interface for the glance_widget plugin.
version: 0.1.0
# TODO: Replace YOUR_GITHUB_USERNAME with your actual GitHub username before publishing
homepage: https://github.com/YOUR_GITHUB_USERNAME/glance_widget
repository: https://github.com/YOUR_GITHUB_USERNAME/glance_widget/tree/master/glance_widget_platform_interface
issue_tracker: https://github.com/YOUR_GITHUB_USERNAME/glance_widget/issues

environment:
  sdk: ^3.10.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
